### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by bjs-pdx** [timkley/tim-kleyersburg.de#29]
Trying to follow your setup process for HomeAssistant docker on Raspberry Pi 4.  When I run sudo docker compose up -d I receive the above message.  I'm running BullsEye 64 bit on the pi but can't get the HA docker to start.  Here is my docker-compose.yml

```
--
version: '2.1'
services:
    homeassistant:
        image: lscr.io/linuxserver/homeassistant
        container_name: homeassistant
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=PST
        volumes:
            - /home/pi/docker/homeAssistant/data:/config
        restart: unless-stopped
```

What am I missing?
